######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 16 12:53:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += login.h
SOURCES += login.cpp main.cpp
