######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 18 10:47:17 2011
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test.h
FORMS += test.ui
SOURCES += main.cpp test.cpp
